config/routes.rb
Rails.application.routes.draw do
  resources :renaisses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/renaiss.rb
class Renaiss < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/renaisses_controller.rb
class RenaissesController < ApplicationController
  before_action :set_renaiss, only: %i[ show edit update destroy ]

  # GET /renaisses or /renaisses.json
  def index
    @renaisses = Renaiss.all
  end

  # GET /renaisses/1 or /renaisses/1.json
  def show
  end

  # GET /renaisses/new
  def new
    @renaiss = Renaiss.new
  end

  # GET /renaisses/1/edit
  def edit
  end

  # POST /renaisses or /renaisses.json
  def create
    @renaiss = Renaiss.new(renaiss_params)

    respond_to do |format|
      if @renaiss.save
        format.html { redirect_to @renaiss, notice: "Renaiss was successfully created." }
        format.json { render :show, status: :created, location: @renaiss }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @renaiss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renaisses/1 or /renaisses/1.json
  def update
    respond_to do |format|
      if @renaiss.update(renaiss_params)
        format.html { redirect_to @renaiss, notice: "Renaiss was successfully updated." }
        format.json { render :show, status: :ok, location: @renaiss }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @renaiss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renaisses/1 or /renaisses/1.json
  def destroy
    @renaiss.destroy!

    respond_to do |format|
      format.html { redirect_to renaisses_path, status: :see_other, notice: "Renaiss was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renaiss
      @renaiss = Renaiss.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def renaiss_params
      params.expect(renaiss: [ :author, :born_died, :title, :date, :technique, :location, :url, :form, :type, :school, :timeframe ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/renaisses_helper.rb
module RenaissesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Renai" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/renaisses/_form.html.erb
<%= form_with(model: renaiss) do |form| %>
  <% if renaiss.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(renaiss.errors.count, "error") %> prohibited this renaiss from being saved:</h2>

      <ul>
        <% renaiss.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.textarea :author %>
  </div>

  <div>
    <%= form.label :born_died, style: "display: block" %>
    <%= form.textarea :born_died %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.textarea :title %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.textarea :date %>
  </div>

  <div>
    <%= form.label :technique, style: "display: block" %>
    <%= form.textarea :technique %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.textarea :location %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.textarea :url %>
  </div>

  <div>
    <%= form.label :form, style: "display: block" %>
    <%= form.textarea :form %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.textarea :type %>
  </div>

  <div>
    <%= form.label :school, style: "display: block" %>
    <%= form.textarea :school %>
  </div>

  <div>
    <%= form.label :timeframe, style: "display: block" %>
    <%= form.textarea :timeframe %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/renaisses/_renaiss.html.erb
<div id="<%= dom_id renaiss %>">
  <p>
    <strong>Author:</strong>
    <%= renaiss.author %>
  </p>

  <p>
    <strong>Born died:</strong>
    <%= renaiss.born_died %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= renaiss.title %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= renaiss.date %>
  </p>

  <p>
    <strong>Technique:</strong>
    <%= renaiss.technique %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= renaiss.location %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= renaiss.url %>
  </p>

  <p>
    <strong>Form:</strong>
    <%= renaiss.form %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= renaiss.type %>
  </p>

  <p>
    <strong>School:</strong>
    <%= renaiss.school %>
  </p>

  <p>
    <strong>Timeframe:</strong>
    <%= renaiss.timeframe %>
  </p>

</div>

app/views/renaisses/edit.html.erb
<% content_for :title, "Editing renaiss" %>

<h1>Editing renaiss</h1>

<%= render "form", renaiss: @renaiss %>

<br>

<div>
  <%= link_to "Show this renaiss", @renaiss %> |
  <%= link_to "Back to renaisses", renaisses_path %>
</div>

app/views/renaisses/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Renaisses" %>

<h1>Renaisses</h1>

<div id="renaisses">
  <% @renaisses.each do |renaiss| %>
    <%= render renaiss %>
    <p>
      <%= link_to "Show this renaiss", renaiss %>
    </p>
  <% end %>
</div>

<%= link_to "New renaiss", new_renaiss_path %>

app/views/renaisses/new.html.erb
<% content_for :title, "New renaiss" %>

<h1>New renaiss</h1>

<%= render "form", renaiss: @renaiss %>

<br>

<div>
  <%= link_to "Back to renaisses", renaisses_path %>
</div>

app/views/renaisses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @renaiss %>

<div>
  <%= link_to "Edit this renaiss", edit_renaiss_path(@renaiss) %> |
  <%= link_to "Back to renaisses", renaisses_path %>

  <%= button_to "Destroy this renaiss", @renaiss, method: :delete %>
</div>